version: "3"
services:
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - monitoring_network
    restart: unless-stopped


  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - monitoring_network
    restart: unless-stopped
  

  cloudwatch-exporter:
    image: prom/cloudwatch-exporter:latest
    container_name: cloudwatch-exporter
    ports:
      - "9106:9106"
    volumes:
      - ./aws-config.yml:/config/config.yml
    environment:  
      AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY}"
      AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"
      AWS_REGION: "${AWS_REGION:-ap-northeast-2}"
    # command:
    #   - '--config.file=/config/config.yml'
    networks:
      - monitoring_network
    restart: unless-stopped
  

  # influxdb-exporter:
  #   image: prom/influxdb-exporter
  #   container_name: influxdb-exporter
  #   ports:
  #     - "9122:9122"
  #   environment:
  #     - INFLUXDB_URL=${INFLUXDB_URL}
  #     - INFLUXDB_USERNAME=
  #     - INFLUXDB_PASSWORD=
  #   networks:
  #     - monitoring_network
  #   restart: unless-stopped
  

networks:
  monitoring_network:
    driver: bridge

volumes:
  grafana-data: