global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'grafana'
    scrape_interval: 5s
    static_configs:
      - targets: ['grafana:3000']

  - job_name: 'cloudwatch-exporter'
    static_configs:
      - targets: ['cloudwatch-exporter:9106']

  - job_name: 'influxdb-exporter'
    static_configs:
      - targets: ['influxdb-exporter:9122']

  - job_name: 'flink'
    static_configs:
      # - targets: ['localhost:9249']
      - targets: ['host.docker.internal:9249']
