{
 "title": "#1",
 "time": { "from": "2025-06-13T07:01:37.794Z", "to": "2025-06-13T07:10:10.794Z" },
 "panels": [
  {
   "title": "Kafka Node Response Rate ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "kafka_consumer_node_response_rate",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Flink Records Out",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_operator_numRecordsOut",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Kafka Consumer Lag",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "kafka_consumergroup_lag", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Flink Records Out per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_operator_numRecordsOutPerSecond",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Flink Records In ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_operator_numRecordsIn",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Flink Records in per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_operator_numRecordsInPerSecond",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Flink BusyTime",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_busyTimeMsPerSecond",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Flink JVM CPU Load",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 13, "x": 0, "y": 38 },
   "targets": [
    {
     "expr": "flink_jobmanager_Status_JVM_CPU_Load",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Flink CPU",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 13, "y": 38 },
   "targets": [
    {
     "expr": "flink_taskmanager_Status_JVM_CPU_Load",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Flink Backpressure",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 44 },
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_backPressuredTimeMsPerSecond",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}