region: ap-northeast-2

metrics:
  # Kinesis Streams
  - aws_namespace: AWS/Kinesis
    aws_metric_name: GetRecords.IteratorAgeMilliseconds
    aws_dimensions: [StreamName]
    aws_statistics: [Maximum, Average]
    period_seconds: 300
    range_seconds: 600
    delay_seconds: 60

  - aws_namespace: AWS/Kinesis
    aws_metric_name: IncomingBytes
    aws_dimensions: [StreamName]
    aws_statistics: [Sum]
    period_seconds: 300
    range_seconds: 600
    delay_seconds: 60

  # IoT Core
  - aws_namespace: AWS/IoT
    aws_metric_name: NumberOfMessagesPublished
    aws_dimensions: [ClientId]
    aws_statistics: [Sum]
    period_seconds: 300
    range_seconds: 600
    delay_seconds: 60

  # S3
  - aws_namespace: AWS/S3
    aws_metric_name: NumberOfObjects
    aws_dimensions: [BucketName, StorageType]
    aws_statistics: [Average]
    period_seconds: 300
    range_seconds: 600
    delay_seconds: 60

  - aws_namespace: AWS/S3
    aws_metric_name: BucketSizeBytes
    aws_dimensions: [BucketName, StorageType]
    aws_statistics: [Average]
    period_seconds: 300
    range_seconds: 600
    delay_seconds: 60
